### PR TITLE
Add KeyDecoder/KeyEncoder for circe

### PR DESCRIPTION
**Pull request by ivan-klass**

### CODE REVIEW

**Comment by kevin-lee** [comment]
Thank you, @ivan-klass, for the PR. Unfortunately, it requires more changes than what you've made. I'll get back to you on this PR after I address the other parts.

**Comment by ivan-klass** [comment]
@kevin-lee could you please list the missing things? May be I can follow up

**Comment by kevin-lee** [comment]
@ivan-klass Sure,
1. Please remove all the test code you added. That's not the correct place to put the test for `auto`.
2. [This](https://github.com/kevin-lee/refined4s/tree/bf2fae178a8703968ec9b3648f4b6a9f7d19f441/modules/refined4s-circe/shared/src/test/scala/refined4s/modules/circe/derivation/generic) is the right place to add the tests. So you need to add tests for `KeyEncoder` and `KeyDecoder` to `CustomTypeSpec.scala`, `networkSpec.scala`, `numericSpec.scala`, and `stringsSpec.scala`.
3. Unfortunately, your current code doesn't compile, please make sure the code compiles.

If you feel that adding tests to all those types is too much and time-consuming, and if you want to have the new `auto` with `KeyEncoder` and `KeyDecoder` released sooner, just let me know. You can keep the code without tests, and I can sort out the tests for a faster release.

**Comment by kevin-lee** [comment]
Also, please don't forget to rebase the current `origin/main`.

**Comment by kevin-lee** [comment]
@ivan-klass Sorry, I had to release a new version to use the `KeyEncoder` and `KeyDecoder`, including the `auto` one. If you're interested, here's how I did it.
https://github.com/kevin-lee/refined4s/pull/371/files

Also all the other `KeyEncoder`s and `KeyDecoder`s.
* https://github.com/kevin-lee/refined4s/pull/360/files
* https://github.com/kevin-lee/refined4s/pull/365/files

**Comment by ivan-klass** [comment]
@kevin-lee thank you very much!

**Pull request closed without merging**
